[package]
name = "async_uws"
version = "0.1.0"
edition = "2021"

[profile.dev.build-override]
debug = true
[profile.release.build-override]
debug = true


[dependencies]
uwebsockets_rs = { path = "../uwebsockets_rs", features = ["native-access"] }
tokio = { version = "1.28.1", features = ["full"] }
